#!/bin/bash
INDIR="/Users/trondarildtjstheim/Documents/Master CogSci/Neuro-modelling, cognitive robotics & agents /Project - robot animation/MAMN10_G8_data-program/Data analysis/DataCleanup/rawdata"

OUTDIR="/Users/trondarildtjstheim/Documents/Master CogSci/Neuro-modelling, cognitive robotics & agents /Project - robot animation/MAMN10_G8_data-program/Data analysis/DataCleanup/humpfiles"


cd bin
java CleanupMain -s "$INDIR/Bjarni_peka_armbage_raw.txt" -t "$OUTDIR/Bjarni_peka_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_peka_axel_raw.txt" -t "$OUTDIR/Bjarni_peka_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_peka_hand_hump.txt" -t "$OUTDIR/Bjarni_peka_hand_hump.csv"
java CleanupMain -s "$INDIR/Bjarni_peka_hand_raw.txt" -t "$OUTDIR/Bjarni_peka_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull21_armbage_raw.txt" -t "$OUTDIR/Bjarni_pull21_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull21_axel_raw.txt" -t "$OUTDIR/Bjarni_pull21_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull21_hand_raw.txt" -t "$OUTDIR/Bjarni_pull21_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull31_armbage_raw.txt" -t "$OUTDIR/Bjarni_pull31_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull31_axel_raw.txt" -t "$OUTDIR/Bjarni_pull31_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull31_hand_raw.txt" -t "$OUTDIR/Bjarni_pull31_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull32_armbage_raw.txt" -t "$OUTDIR/Bjarni_pull32_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull32_axel_raw.txt" -t "$OUTDIR/Bjarni_pull32_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_pull32_hand_raw.txt" -t "$OUTDIR/Bjarni_pull32_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push12_armbage_raw.txt" -t "$OUTDIR/Bjarni_push12_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push12_axel_raw.txt" -t "$OUTDIR/Bjarni_push12_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push12_hand_raw.txt" -t "$OUTDIR/Bjarni_push12_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push13_armbage_raw.txt" -t "$OUTDIR/Bjarni_push13_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push13_axel_raw.txt" -t "$OUTDIR/Bjarni_push13_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push13_hand_raw.txt" -t "$OUTDIR/Bjarni_push13_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push23_armbage_raw.txt" -t "$OUTDIR/Bjarni_push23_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push23_axel_raw.txt" -t "$OUTDIR/Bjarni_push23_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_push23_hand_raw.txt" -t "$OUTDIR/Bjarni_push23_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove1_armbage_raw.txt" -t "$OUTDIR/Bjarni_shove1_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove1_axel_raw.txt" -t "$OUTDIR/Bjarni_shove1_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove1_hand_raw.txt" -t "$OUTDIR/Bjarni_shove1_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove2_armbage_raw.txt" -t "$OUTDIR/Bjarni_shove2_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove2_axel_raw.txt" -t "$OUTDIR/Bjarni_shove2_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove2_hand_raw.txt" -t "$OUTDIR/Bjarni_shove2_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove3_armbage_raw.txt" -t "$OUTDIR/Bjarni_shove3_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove3_axel_raw.txt" -t "$OUTDIR/Bjarni_shove3_axel_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_shove3_hand_raw.txt" -t "$OUTDIR/Bjarni_shove3_hand_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_sweep1_armbage_raw.txt" -t "$OUTDIR/Bjarni_sweep1_armbage_raw.csv"
java CleanupMain -s "$INDIR/Bjarni_sweep1_axel_raw_useless.txt" -t "$OUTDIR/Bjarni_sweep1_axel_raw_useless.csv"
java CleanupMain -s "$INDIR/Bjarni_sweep1_hand_raw.txt" -t "$OUTDIR/Bjarni_sweep1_hand_raw.csv"
